Feature/streamline icons
digipolisantwerp/location-viewer_widget_angular pull request #19
Opened 2021-05-07 15:28 UTC by TriangleJuice

2021-05-10 08:41 UTC, vademo requested changes

2021-05-10 08:41 UTC, vademo commented on package.json
> +    "@acpaas-ui/ngx-icon": "^4.0.0",
- [ ] Zelfde comment als bij andere pr, deze module is nog niet gepubliceerd.

2021-05-10 09:35 UTC, GlennDigipolis commented on projects/ngx-location-viewer/src/lib/classes/location-viewer-map.ts
> +    return `<span style="${markerStyle}" class="ngx-location-viewer-marker">${markerIcon}</span>`;
Icoon wordt niet correct weergegeven, lijkt alsof geen styling wordt toegepast.

2021-05-10 09:36 UTC, GlennDigipolis commented on projects/ngx-location-viewer/src/lib/classes/location-viewer-map.ts
> +          const htmlIcon = this.getHtmlMarker(marker.color, marker.icon ? `fa-${marker.icon}` : undefined, marker.size, undefined);
`fa-${marker.icon}` ==> nog een verwijzing naar font-awesome

2021-05-10 09:38 UTC, GlennDigipolis commented on projects/ngx-location-viewer/src/lib/components/ngx-location-viewer.component.ts
> +                  this.leafletMap.getHtmlMarker('#000000', 'fa-circle', '10px', { top: '-3px', left: '2px' }),
`fa-circle` hier aanpassen naar relevant ai-icon (cirkel)

2021-05-10 09:39 UTC, GlennDigipolis commented on projects/ngx-location-viewer/src/lib/types/operational-layer-options.model.ts
> +  /* font-awesome icon class eg: fa-map-markern have to provide valid icon class otherwise marker won't be visible */
description van icon hier nog aanpassen naar passende beschrijving voor ai-icon

2021-06-16 13:52 UTC, jschoubben commented on README.md
> +<link rel="stylesheet" href="https://cdn.antwerpen.be/core_branding_scss/5.0.0/main.min.css">
5.0.1?

2021-06-16 13:54 UTC, jschoubben approved these changes

2021-06-17 07:46 UTC, GlennDigipolis approved these changes

2021-06-17 07:56 UTC, merged